# Site settings
title: Lost in my Terminal
email: wendellspam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All the things I slowly discovered while trying to get things done at a Linux or Mac
  terminal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wackywendell.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wackywendell

# Build settings
markdown: kramdown
