# Site settings
title: Lost in my Terminal
email: wendell@lostinmyterminal.com
description: > # this means to ignore newlines until "baseurl:"
  Some things I've learned while engineering...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lostinmyterminal.com" # the base hostname & protocol for your site
author: Wendell Smith
#twitter_username: jekyllrb
github_username: wackywendell
linkedin_username: wwendell

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["bower_components"]

kramdown:
  math_engine: mathjax
