# Site settings
title: Lost in my Terminal
email: wendell@lostinmyterminal.com
description: > # this means to ignore newlines until "baseurl:"
  All the things I slowly discovered while trying to get things done at a BASH or ZSH
  terminal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lostinmyterminal.com" # the base hostname & protocol for your site
author: Wendell Smith
#twitter_username: jekyllrb
github_username:  wackywendell

# Build settings
markdown: kramdown
# Use Pygments. Default for Github.
highlighter: pygments
exclude: ['bower_components']
